**Introduction**

This notebook explores the functionalities of the NumPy library. 

In [6]:
#importing NumPy

import numpy as np

In [17]:

#Creating an Array

a = np.array([[1,2,3], [4,5,6]])

a.shape

#all elements of the array must be of the same type of data
#once created, the total size of the array can't change
#the shape must be 'rectangular', not 'jagged'.i.e.each row of a 2D array must have the same number of columns

(2, 3)

**Array Fundamentals**

In [ ]:
a = np.array([1,2,3,4,5,6]) #1D vector with 6 elements

#indexing

a[0]

#The array is mutable 

a[0] = 10

#Like in a list, the slice notatio can be used for indexing

a[:3]

#Slicing a list returns a new list but slicing an array returns a view of the original array.

#The original array can be mutated using the view. 

b = a[3:]

b[0] = 40

a

a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9, 10, 11, 12]])

#Dimension of an array is referred to an 'axis'. Eg: array a technically represents 3 points in 4D space, but a has only two 'axes'

#Accessing 8

a[1,3] #Indexing for rows and elements both begins at zero: first row, third column






8

**Array attributes**

In [ ]:
#Covers ndim, shape, size and dtype attributes of an array

#finding the dimensions of an array (ndim)

print(a.ndim)

#checking the shape of an array(shape)

len(a.shape) == a.ndim


a = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

len(a.shape) == a.ndim


#Finding the size i.e the number of elements in an array (multiplying the number of rows and columns)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.size)

import math

a.size == math.prod(a.shape)

#Arrays are typically homogeneous i.e they contain elements of only one 'data type' 

a.dtype



2
12


dtype('int64')

**Creating a basic array**

In [128]:
#np.zeros(), np.ones(), np.empty(), np.arange(). np.linspace()

##creating an array filled with zeros

np.zeros(2)

##creating an array filled with ones and specifying the datatype

print(np.ones(2, dtype=np.int64))

##creating an empty array with 2 elements

np.empty(2) #generates random numbers

##creating an array with a range of elements

np.arange(4, dtype = np.float64)

np.arange(2,9,2)

##creating an array with values that are linearly spaced in a specified interval

np.linspace(0, 10, num = 5)


[1 1]


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Adding,removing, and sorting elements**

In [ ]:
#covers np.sort(), np.concatenate()

arr = np.array([2,1,5,3,7,4,6,8])

#sorting the numbers in ascending order

np.sort(arr)

#concatenating 
a = np.array([[1,2], [3,4]])
b =  np.array([[5,6]])

np.concatenate((a,b), axis = 0)


array([[1, 2],
       [3, 4],
       [5, 6]])

**Shape and size of an array**

In [ ]:
#covers ndarray.ndim, ndarray.size, ndarray.shape

array_example = np.array([[[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]]])

#finding the number of dimensions of the array
array_example.ndim

##finding the total number of elements in the array

array_example.size

##finding the shape of an array

array_example.shape

(3, 2, 4)

**Reshaping an array**

In [78]:
##covers arr.reshape()

a = np.arange(6)
print(a)

b = a.reshape(3,2)
print(b)

np.reshape(a, newshape=(1,6), order = 'C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

**How to convert a 1D array into a 2D array (how to add a new axis to an array)**

In [ ]:
#covers np.newaxis(), np.expand_dims to increase the dimensions of the existing array

a = np.array([1,2,3,4,5,6])

a.shape

#adding a new dimension to the array

a2 = a[np.newaxis, : ] 

a2 = a[:, np.newaxis ] 

a2.shape

##Expanding the dimensions to add an axis to index position 1

b = np.expand_dims(a, axis=0)
b.shape



(1, 6)

**Indexing and slicing**

In [ ]:
data = np.array([1,2,3])

data[1]

data[0:2]

data[1:]

data[-2:]

#selecting values from the array that fulfill certain conditions

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

##printing all the values in the array that are less than 5

print(a[a<5])

five_up = a[a>=5]

print(five_up)

#print(a[a>=5])

print(a[a % 2 == 0])

##selecting elements that satisfy two conditions using | and & operators to return boolean values that specify whether or not the values in an array fulfill a certain condition

five_up = (a<5) | (a==5)

print(five_up)

#np.nonzero()can also be used to select elements from an array

b = np.nonzero(a<5) #print the indices of elements that are less than 5: row indices, column indices

print(b)

##generating a list of coordinates where the elements exist

list_of_coordinates = list(zip(b[0],b[1]))
print(list_of_coordinates)

for coord in list_of_coordinates:
    print(coord)
    
#np.nonzero to print the elements in a that are less than 5

print(a[b])


[0 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 0  2  4  6  8 10 12]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
[(0, 0), (0, 1), (0, 2), (0, 3)]
(0, 0)
(0, 1)
(0, 2)
(0, 3)
[0 2 3 4]


**Creating an array from existing data**

In [ ]:
#covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(),.copy()

##creating a new array from the section of an existing array

a = np.array([1,2,3,4,5,6,7,8,9,10])

arr1 = a[3:8]
arr1

#stacking 2 existing arrays vertically and horizontally

a1= np.array([[1,1],
              [2,2]])

a2 = np.array([[3,3],
               [4,4]])

print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

##splitting an array into several smaller arrays using hsplit

x = np.arange(1,25).reshape(2,12)
print(x)

###splitting x into 3 equally shaped arrays

np.hsplit(x,3)
np.hsplit(x,(3,4)) #0:2,3:4,4:

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a.shape

b = a[0,:] #viewing and modifying an array

b[0] = 99
print(a)

##making a copy of an array; does not modify the original array 

b2 = a.copy()

b2

b2[0,0]= 100
b2
a



[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Basic Array Operations**

In [ ]:
##covers addition, subtraction, multiplication, division and more

data = np.array([1,2])

ones = np.ones(2, dtype = np.int64)

data + ones
data - ones
data * ones
data / ones
data * data

##finding the sum of the elements in an array

b = np.array([[1,1], [2,2]])

b.sum(axis = 0) #along the axis of rows: goes through different rows

b.sum(axis = 1) #along the axis of columns : goes through the columns


array([3, 3])